In [7]:
class test(object):
    def __init__(self, a, b):
        self._a = a
        self._b = b

In [8]:
o = test(3, 5)

In [9]:
o._a
o._b

5

In [10]:
import numpy as n

In [29]:
a = n.random.rand(10, 10)

In [30]:
a

array([[ 0.36403673,  0.31432938,  0.10366021,  0.28803053,  0.20481512,
         0.99883266,  0.58799934,  0.8599588 ,  0.30009749,  0.68859109],
       [ 0.8354738 ,  0.03392913,  0.53873392,  0.75728177,  0.74211336,
         0.04652583,  0.3672305 ,  0.16055328,  0.56700767,  0.46419724],
       [ 0.90250794,  0.39874391,  0.82732454,  0.06712742,  0.98861866,
         0.75515029,  0.5026417 ,  0.46792408,  0.53922631,  0.55712658],
       [ 0.4493781 ,  0.254687  ,  0.4041079 ,  0.37258889,  0.65700955,
         0.25585722,  0.5376999 ,  0.56522175,  0.38320743,  0.23982382],
       [ 0.87934616,  0.47817947,  0.02023665,  0.83617821,  0.06343393,
         0.27207344,  0.5981313 ,  0.37618292,  0.01614614,  0.25673569],
       [ 0.81477437,  0.10108912,  0.71402746,  0.86859127,  0.53352671,
         0.82206657,  0.08706391,  0.52686929,  0.56238675,  0.24894972],
       [ 0.48161148,  0.25437042,  0.09068965,  0.76326512,  0.75505032,
         0.9088495 ,  0.69219858,  0.94586422

In [31]:
a_norm = a.sum(axis = 1)

In [32]:
a_norm

array([ 4.71035135,  4.51304652,  6.00639143,  4.11958156,  3.79664391,
        5.27934516,  5.75079587,  3.1151418 ,  5.33004105,  5.55905145])

In [33]:
a = a / a_norm[:, n.newaxis]

In [26]:
aa

array([[ 0.2260233 ,  0.02781399,  0.01411422,  0.0909101 ,  0.05883769,
         0.10806298,  0.03376653,  0.22123536,  0.06077574,  0.1584601 ],
       [ 0.1114347 ,  0.14416164,  0.16034378,  0.06465728,  0.08461817,
         0.03835179,  0.02329676,  0.13564101,  0.12695902,  0.11053584],
       [ 0.03265032,  0.12961107,  0.14186305,  0.14797485,  0.10130295,
         0.16366445,  0.01645009,  0.14632158,  0.06718692,  0.05297472],
       [ 0.1496753 ,  0.11906936,  0.0167699 ,  0.08079583,  0.06352465,
         0.00088853,  0.12808156,  0.15928026,  0.11166222,  0.17025239],
       [ 0.19978269,  0.00335211,  0.06785957,  0.17185571,  0.11948012,
         0.0779632 ,  0.07418808,  0.07550673,  0.07098251,  0.13902928],
       [ 0.13694187,  0.15417256,  0.07512185,  0.06017235,  0.06019686,
         0.08158617,  0.08587615,  0.15027903,  0.14372667,  0.0519265 ],
       [ 0.11634793,  0.08424815,  0.19531412,  0.14294976,  0.00758085,
         0.21190903,  0.0307826 ,  0.11943581

In [27]:
aa_norm = aa.sum(axis = 1)

In [28]:
aa_norm

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [34]:
b = a * 0.3 + aa * 0.7

In [35]:
b

array([[ 0.18140163,  0.03948928,  0.01648202,  0.0819816 ,  0.05423096,
         0.13925925,  0.06108596,  0.20963511,  0.06165608,  0.1547781 ],
       [ 0.13354152,  0.10316855,  0.14805241,  0.0955996 ,  0.10856392,
         0.02993901,  0.04071899,  0.10562132,  0.12656255,  0.10823211],
       [ 0.0679326 ,  0.11064373,  0.14062634,  0.10693519,  0.1202904 ,
         0.15228245,  0.0366204 ,  0.12579642,  0.07396347,  0.06490899],
       [ 0.13749774,  0.10189561,  0.04116725,  0.0836901 ,  0.09231262,
         0.01925425,  0.12881397,  0.15265728,  0.10606984,  0.13664134],
       [ 0.20933132,  0.04013086,  0.04910074,  0.18637142,  0.08864845,
         0.07607271,  0.09919429,  0.08257962,  0.05096358,  0.11760702],
       [ 0.14215905,  0.11366521,  0.09316007,  0.09147854,  0.07245558,
         0.10382444,  0.06506073,  0.13513479,  0.13256643,  0.05049518],
       [ 0.10656763,  0.07224337,  0.14145086,  0.13988185,  0.04469507,
         0.19574799,  0.05765753,  0.13294768

In [36]:
b_n = b.sum(axis = 1)

In [37]:
b_n

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
import numpy as np
a = np.random.rand(10,6)

In [53]:
b = [1,2,3,7]
c = a[b,:]
c
d = [1,2,4]
e = c[:, d]
e

array([[ 0.07748306,  0.07820119,  0.2005959 ],
       [ 0.45575163,  0.33789766,  0.95553582],
       [ 0.2151068 ,  0.22443878,  0.61328906],
       [ 0.47905037,  0.01993848,  0.16143269]])

In [48]:
c = np.dot(a,b)

In [49]:
c

array([[ 0.33038714],
       [ 0.50194201],
       [ 0.61187695],
       [ 0.96729556],
       [ 0.30959315]])

In [12]:
c = c[:,np.newaxis]

In [13]:
c

array([[ 2.87782881],
       [ 2.28121865]])

In [2]:
import numpy as np
a = np.random.rand(10,10)

In [11]:
m = [1,2,5,6]
n = [1,8,9]
nn = [[x] for x in n]

In [15]:
b = a[m, :][:, n]

In [7]:
a[m, :][:, n] = a[m, :][:, n] * 2

In [16]:
b

array([[ 0.32674012,  0.26369447,  0.61507028],
       [ 0.69113569,  0.67156418,  0.61384009],
       [ 0.53156392,  0.56861522,  0.50772986],
       [ 0.18602557,  0.23371377,  0.34208147]])

In [17]:
b[2][1]

0.56861521729450115

In [19]:
a = np.random.randint(5, size=(3,5))

In [20]:
a

array([[0, 2, 4, 0, 2],
       [4, 2, 4, 1, 1],
       [4, 4, 1, 1, 3]])

In [23]:
a.sum(axis=0)

array([8, 8, 9, 2, 6])

In [97]:
%%timeit
a = np.random.rand(100,100000)
b = np.random.rand(100,100000)

1 loops, best of 3: 297 ms per loop


In [105]:
m = np.random.binomial(1, 0.5, 100000)
n = [x for x in range(100000) if m[x] == 1]

In [98]:
%%timeit
a = np.random.rand(100,100000)
b = np.random.rand(100,100000)
a = a * 0.7  + b * 0.3

1 loops, best of 3: 424 ms per loop


In [106]:
%%timeit
a[:,n] = a[:,n] * 0.7 + b[:,n] * 0.3

10 loops, best of 3: 137 ms per loop


In [87]:
len(n)

10066

In [45]:
len(e)

506

In [1]:
import numpy as np
a = np.random.rand(10,10)
b = np.random.rand(10,10)

In [2]:
lt = [1,2,4,7,9]

In [5]:
a_norm = a.sum(axis=1)

In [4]:
a /= a_norm[:, np.newaxis]

In [6]:
a_norm

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
a_t = a[:, lt]
a_t_sum = a_t.sum(axis=1)

In [8]:
b_t = b[:, lt]
b_t_norm = b_t.sum(axis=1)
b_t /= b_t_norm[:,np.newaxis]

In [10]:
b_t *= a_t_sum[:, np.newaxis]

In [11]:
a[:, lt] = a_t * 0.7 + b_t * 0.3

In [12]:
a_norm = a.sum(axis=1)

In [13]:
a_norm

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
a = list()
type(a)

list