In [1]:
import numpy as np

In [79]:
K = 6
V = 10

In [156]:
a = np.random.rand(K,V)

In [157]:
a_nor = a.sum(axis=1)
a /= a_nor[:, np.newaxis]

In [127]:
b = np.zeros((K, V))

In [128]:
c = np.random.binomial(1, 0.4, (K, V))

In [129]:
d = np.random.binomial(1, 0.4, V)

In [130]:
e = np.empty((K, V))

In [131]:
f =np.random.binomial(1, 0.4, K)

In [132]:
g = np.empty((K, V))

In [133]:
for v in range(V):
    g[:, v] = f

In [134]:
for k in range(K):
    e[k] = d

In [135]:
h = np.random.rand(K,V)

In [136]:
h *= e

In [137]:
h *= g

In [138]:
ids = list()
topics = list()

In [148]:
for j in xrange(V):
    if (d[j] != 0):
        ids.append(j)

In [139]:
topics_list = []
k =np.random.binomial(1, 0.8, K)
for j in xrange(K):
    if (k[j] != 0):
        topics_list.append(j)

In [140]:
for k in topics_list:
    sum_beta_k = sum(h[k,:])
    if sum_beta_k != 0:
        print sum_beta_k
        h[k,:] /= sum_beta_k
        topics.append(k)

1.90881418387
1.78799671073


In [141]:
topics

[0, 4]

In [142]:
a

array([[ 0.14170763,  0.15504012,  0.08714817,  0.01561604,  0.00489322,
         0.10344354,  0.00893731,  0.18127845,  0.08724087,  0.21469465],
       [ 0.06668734,  0.11990441,  0.02866513,  0.05694428,  0.0816893 ,
         0.21827084,  0.08549003,  0.01808967,  0.168521  ,  0.155738  ],
       [ 0.02479968,  0.032305  ,  0.03979548,  0.18422242,  0.08461919,
         0.18324666,  0.17418716,  0.15752091,  0.03480325,  0.08450024],
       [ 0.07569766,  0.1230848 ,  0.12790362,  0.04820301,  0.13782266,
         0.00559014,  0.12649705,  0.07868797,  0.13842878,  0.1380843 ],
       [ 0.221303  ,  0.15668132,  0.10293653,  0.12775625,  0.04000931,
         0.04127648,  0.07784709,  0.14403152,  0.0154842 ,  0.07267432],
       [ 0.03971273,  0.09266297,  0.08924821,  0.20659393,  0.17158985,
         0.08260972,  0.00699758,  0.0062778 ,  0.13112329,  0.17318392]])

In [144]:
a[topics,:] *= (1 - rhot)

In [102]:
a

array([[ 0.16539651,  0.14400335,  0.01720142,  0.11556578,  0.0929408 ,
         0.05502508,  0.15991379,  0.08977414,  0.11549069,  0.04468844],
       [ 0.06406924,  0.05418421,  0.04777618,  0.04909555,  0.01441569,
         0.18782073,  0.02855943,  0.11444516,  0.07438532,  0.0152485 ],
       [ 0.00646512,  0.08814394,  0.07361764,  0.11407132,  0.0614027 ,
         0.10866488,  0.04395178,  0.03605337,  0.10563563,  0.01199362],
       [ 0.08479757,  0.12380703,  0.14213323,  0.05415127,  0.06732672,
         0.05083374,  0.11904422,  0.11084818,  0.12033915,  0.12671889],
       [ 0.07819784,  0.03538324,  0.11280902,  0.10527406,  0.06496782,
         0.04563668,  0.02730135,  0.04029371,  0.03129746,  0.10883883],
       [ 0.12687127,  0.05457841,  0.17256105,  0.03999495,  0.11411116,
         0.14964307,  0.03636587,  0.12436388,  0.02553204,  0.1559783 ]])

In [147]:
a.sum(axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [160]:
k =  h[topics, :][:, ids] * rhot

In [111]:
idss = [[i] for i in ids]

In [167]:
topicss = [[j] for j in topics]

In [149]:
a[:,ids]

array([[ 0.13900222,  0.18530552,  0.12679207],
       [ 0.06668734,  0.0816893 ,  0.08549003],
       [ 0.02479968,  0.08461919,  0.17418716],
       [ 0.07569766,  0.13782266,  0.12649705],
       [ 0.2685306 ,  0.11801246,  0.18391055],
       [ 0.03971273,  0.17158985,  0.00699758]])

In [170]:
a[topicss,ids] += k

In [152]:
a[:,ids] = a[:, ids] + a[:, ids]

In [169]:
k

array([[ 0.04689226,  0.18212493,  0.12098281],
       [ 0.12468365,  0.09200641,  0.13330994]])

In [184]:
a[[1,2], :]

array([[ 5.08006905,  5.15199371,  5.03756641,  5.10684403,  5.05306015,
         5.15625603,  5.15306319,  5.03744128,  5.13260395,  5.0911022 ],
       [ 3.17062874,  3.15938615,  3.13007334,  3.00418676,  3.15966326,
         3.06350977,  3.07794627,  3.08307042,  3.05690559,  3.0946297 ]])

In [166]:
topicss

[[1], [2], [4]]

In [171]:
a.sum(axis=1)

array([ 1.35,  1.  ,  1.  ,  1.  ,  1.35,  1.  ])