In [1]:
import numpy as np

In [5]:
arr = np.arange(10000)

In [6]:
np.random.shuffle(arr)

In [7]:
arr

array([8882, 7605, 9743, ...,  401, 1455, 2693])

In [9]:
arr = np.arange(18).reshape((6, 3))

In [10]:
np.random.shuffle(arr)

In [11]:
arr

array([[12, 13, 14],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [23]:
rand_n = np.random.choice([1,23,4,5,6,7, 2 ,4,11], 5, False)

In [24]:
type(rand_n)

numpy.ndarray

In [20]:
rand_n.sort()

In [25]:
rand_n

array([2, 7, 4, 1, 5])

In [26]:
rand_n = np.sort(rand_n)

In [27]:
rand_n

array([1, 2, 4, 5, 7])

In [30]:
rand_n = np.delete(rand_n, 0)

In [31]:
rand_n

array([4, 5, 7])

In [38]:
def get_list_doc_index_above_a_length(file_path, min_length=5):
    num_docs_count = 0
    list_index = []
    for idx, line in enumerate(open(file_path, 'r')):
        tokens = line.strip().split()
        if len(tokens) >= min_length:
            list_index.append(idx)
        num_docs_count += 1
    return num_docs_count, list_index

In [39]:
file_path = 'nyt_50k.txt'

In [40]:
numdocs , list_dix = get_list_doc_index_above_a_length(file_path)

In [41]:
numdocs

50000

In [42]:
len(list_dix)

49956

In [1]:
import time

In [15]:
time.strftime("%Y%m%d")

'20161201'

In [16]:
a = [1,4,6,7,8,34,2,4,4]

In [20]:
a[1:]

[4, 6, 7, 8, 34, 2, 4, 4]