In [2]:
import numpy as np

In [3]:
N_phi = np.random.rand(5,10)

In [4]:
N_Z = N_phi.sum(axis=1)

In [5]:
N_Z

array([ 4.95009749,  4.40757214,  6.16232152,  5.66322717,  4.16932115])

In [6]:
N_Z[[1,2,4]]

array([ 4.40757214,  6.16232152,  4.16932115])

In [14]:
gamma_ij = N_phi[:, 2,4]

IndexError: too many indices for array

In [13]:
gamma_ij

array([[ 0.25171912,  0.75423839],
       [ 0.7153815 ,  0.66257077],
       [ 0.56536574,  0.92125335],
       [ 0.56970143,  0.5104134 ],
       [ 0.78580213,  0.847258  ]])

In [9]:
N_phi

array([[ 0.45763389,  0.1577395 ,  0.25171912,  0.92154244,  0.75423839,
         0.2723736 ,  0.68795694,  0.81057699,  0.61480506,  0.02151156],
       [ 0.90002482,  0.65347216,  0.7153815 ,  0.77395585,  0.66257077,
         0.15494079,  0.24892658,  0.04742706,  0.23561559,  0.01525701],
       [ 0.54018692,  0.67494667,  0.56536574,  0.15597109,  0.92125335,
         0.66663719,  0.79591842,  0.87144575,  0.28840682,  0.68218957],
       [ 0.45740204,  0.20828873,  0.56970143,  0.79309889,  0.5104134 ,
         0.18101521,  0.86983039,  0.48648997,  0.9046554 ,  0.68233173],
       [ 0.82559606,  0.38840684,  0.78580213,  0.10512852,  0.847258  ,
         0.11488152,  0.41009803,  0.08535354,  0.57833301,  0.0284635 ]])