In [3]:
import numpy as np
from scipy.ndimage.interpolation import shift

xs = np.array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

ys = shift(xs, 3, cval=0.)

In [2]:
xs

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [7]:
xsi = xs.astype(int)

In [8]:
xsi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ysi = shift(xsi, -3, cval=0)

In [18]:
ysi

array([3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

In [13]:
ssi = ysi - xsi

In [14]:
ssi

array([ 0, -1, -2, -3, -3, -3, -3, -3, -3, -3])

In [15]:
assi = np.absolute(ssi)

In [16]:
assi

array([0, 1, 2, 3, 3, 3, 3, 3, 3, 3])

In [19]:
def aver_mag_diff(speech, start, N=512):
    pass

In [22]:
np.sum(assi[:3])

3

In [ ]:
def 