In [2]:
import numpy as np
from scipy.ndimage.interpolation import shift

xs = np.array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

ys = shift(xs, 3, cval=0.)

In [3]:
xs

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [4]:
xsi = xs.astype(int)

In [5]:
xsi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
ysi = shift(xsi, -3, cval=0)

In [7]:
ysi

array([3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

In [8]:
ssi = ysi - xsi

In [9]:
ssi

array([ 3,  3,  3,  3,  3,  3,  3, -7, -8, -9])

In [10]:
assi = np.absolute(ssi)

In [11]:
assi

array([3, 3, 3, 3, 3, 3, 3, 7, 8, 9])

In [12]:
def aver_mag_diff(speech, start, N=512):
    pass

In [13]:
np.sum(assi[:3])

9

In [26]:
def energy_in_frame(signal, frame_size=256):
    sig_len = len(signal)
    sig_square = np.square(signal)
    energy = np.zeros(sig_len)
    for start in range(sig_len - frame_size):
        energy[start] = np.sum(sig_square[start:start + frame_size])
    return energy

In [15]:
np.square(assi)

array([ 9,  9,  9,  9,  9,  9,  9, 49, 64, 81])

In [17]:
from scipy.io import wavfile
file_name = 'Xe.wav'
rate, data = wavfile.read(file_name)

In [18]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
frame_size = 256
num_samples = len(data)

In [51]:
energy = energy_in_frame(data, 256)

In [45]:
sig = signal.astype('int64')

In [46]:
sig

array([ -86,  -98, -105, ...,  -86, -106, -105])

In [49]:
data = sig

In [60]:
def zero_crossing(signal, frame_size=256):
    num_samples = len(signal)
    flag = 1
    if signal[0] < 0:
        flag = -1
    zcr_point = np.zeros(num_samples)
    for x in range(num_samples-1):
        if signal[x+1] >= 0:
            new_flag = 1
        else:
            new_flag = -1
        if new_flag != flag:
            zcr_point[x] = 1
            flag = new_flag
    zcr = np.zeros(num_samples)
    for start in range(num_samples - frame_size):
        zcr[start] = np.sum(zcr_point[start: start+frame_size])
    return zcr

In [73]:
import matplotlib
matplotlib.use('TkAgg')

from numpy import arange, sin, pi
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

import sys
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk


def destroy(e):
    sys.exit()

root = Tk.Tk()
root.wm_title("Embedding in TK")
t = np.arange(num_samples)
f = Figure(figsize=(5, 4), dpi=100)
a = f.add_subplot(311)
b = f.add_subplot(312)
c = f.add_subplot(313)

a.plot(t, data)
a.set_title('Speech signal')
a.set_xlabel('samples')
a.set_ylabel('magtitude')

b.plot(t, energy)
b.set_title('energy')
b.set_xlabel('samples')
b.set_ylabel('e')

c.plot(t, zcr)
c.set_title('zcr')
c.set_xlabel('samples')
c.set_ylabel('zcr')


# a tk.DrawingArea
canvas = FigureCanvasTkAgg(f, master=root)
canvas.show()
canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

# button = Tk.Button(master=root, text='Quit', command=sys.exit)
button = Tk.Button(master=root, text='Quit', command=root.destroy)
button.pack(side=Tk.BOTTOM)

Tk.mainloop()

In [68]:
zcr = zero_crossing(sig)

In [65]:
from scipy.ndimage.interpolation import shift
zcr_s1 = shift(zcr, 1, cval=0)
zcr_d = zcr - zcr_s1

In [69]:
zcr

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])