In [1]:
import numpy as np
from scipy.ndimage.interpolation import shift

xs = np.array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

ys = shift(xs, 3, cval=0.)

In [2]:
xs

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [3]:
xsi = xs.astype(int)

In [4]:
xsi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ysi = shift(xsi, -3, cval=0)

In [6]:
ysi

array([3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

In [7]:
ssi = ysi - xsi

In [8]:
ssi

array([ 3,  3,  3,  3,  3,  3,  3, -7, -8, -9])

In [9]:
assi = np.absolute(ssi)

In [10]:
assi

array([3, 3, 3, 3, 3, 3, 3, 7, 8, 9])

In [11]:
def aver_mag_diff(speech, start, N=512):
    pass

In [12]:
np.sum(assi[:3])

9

In [62]:
from scipy.io import wavfile
# file_name = 'Xe.wav'
file_name = 'A96.wav'
rate, signal = wavfile.read(file_name)

In [88]:
def energy_in_frame(signal, frame_size=256, step=128):
    sig_len = len(signal)
    sig_square = np.square(signal)
    energy = np.zeros(sig_len)
    for start in range(0,sig_len - frame_size, step):
        energy[start] = np.sum(sig_square[start:start + frame_size])
    return energy

In [64]:
np.square(assi)

array([ 9,  9,  9,  9,  9,  9,  9, 49, 64, 81])

In [65]:
import numpy as np

In [66]:
frame_size = 256
num_samples = len(signal)

In [67]:
signal = signal.astype('int64')

In [68]:
energy = energy_in_frame(signal, 256)

In [69]:
def zero_crossing(signal, frame_size=256, step=256):
    num_samples = len(signal)
    flag = 1
    if signal[0] < 0:
        flag = -1
    zcr_point = np.zeros(num_samples)
    for x in range(num_samples-1):
        if signal[x+1] >= 0:
            new_flag = 1
        else:
            new_flag = -1
        if new_flag != flag:
            zcr_point[x] = 1
            flag = new_flag
    zcr = np.zeros(num_samples)
    for start in range(0,num_samples - frame_size, step):
        zcr[start] = np.sum(zcr_point[start: start+frame_size])
    return zcr

In [70]:
zcr = zero_crossing(signal)

In [71]:
from scipy.ndimage.interpolation import shift
zcr_s1 = shift(zcr, 20, cval=0)
zcr_l1 = shift(zcr, -20, cval=0)
zcr_d = 2 * zcr - zcr_s1 - zcr_l1

In [72]:
print zcr[1000], ' ', zcr[1001], ' ', zcr[1002]
print zcr_s1[1002]
print zcr_l1[1000]
print zcr_d[1001]

0.0   0.0   0.0
1.76324152623e-38
5.55111512313e-17
3.33066907388e-16


In [44]:
import sys
sys.path

['',
 '/home/cuonghn/anaconda2/lib/python27.zip',
 '/home/cuonghn/anaconda2/lib/python2.7',
 '/home/cuonghn/anaconda2/lib/python2.7/plat-linux2',
 '/home/cuonghn/anaconda2/lib/python2.7/lib-tk',
 '/home/cuonghn/anaconda2/lib/python2.7/lib-old',
 '/home/cuonghn/anaconda2/lib/python2.7/lib-dynload',
 '/home/cuonghn/anaconda2/lib/python2.7/site-packages',
 '/home/cuonghn/anaconda2/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg',
 '/home/cuonghn/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',
 '/home/cuonghn/anaconda2/lib/python2.7/site-packages/IPython/extensions',
 '/home/cuonghn/.ipython']

In [45]:
import audiolazy

In [46]:
import pyaudio

In [49]:
import pyaudio
import wave
import sys

# length of data to read.
chunk = 1024

'''
************************************************************************
      This is the start of the "minimum needed to read a wave"
************************************************************************
'''
# open the file for reading.
file_name2 = 'A96.wav'
wf = wave.open(file_name2, 'rb')

# create an audio object
p = pyaudio.PyAudio()

# open stream based on the wave object which has been input.
stream = p.open(format =
                p.get_format_from_width(wf.getsampwidth()),
                channels = wf.getnchannels(),
                rate = wf.getframerate(),
                output = True)

# read data (based on the chunk size)
data = wf.readframes(chunk)

# play stream (looping from beginning of file to the end)
while data != '':
    # writing to the stream is what *actually* plays the sound.
    stream.write(data)
    data = wf.readframes(chunk)

# cleanup stuff.
stream.close()    
p.terminate()

In [74]:
class AudioFile(object):
    chunk = 1024

    def __init__(self, file):
        """ Init audio stream """ 
        self.wf = wave.open(file, 'rb')
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(
            format = self.p.get_format_from_width(self.wf.getsampwidth()),
            channels = self.wf.getnchannels(),
            rate = self.wf.getframerate(),
            output = True
        )

    def play(self):
        """ Play entire file """
        data = self.wf.readframes(self.chunk)
        while data != '':
            self.stream.write(data)
            data = self.wf.readframes(self.chunk)

    def close(self):
        """ Graceful shutdown """ 
        self.stream.close()
        self.p.terminate()

# Usage example for pyaudio
a = AudioFile("Xe.wav")
a.play()
a.close()

In [86]:
import matplotlib
matplotlib.use('TkAgg')

from numpy import arange, sin, pi
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

import sys
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk


def destroy(e):
    sys.exit()
def tk_lpc(file_name, root):
#     root = Tk.Tk()
    root.wm_title("Embedding in TK")
    
    f = Figure(figsize=(5, 4), dpi=100)
    a = f.add_subplot(311)
    b = f.add_subplot(312)
    c = f.add_subplot(313)
    
    rate, signal = wavfile.read(file_name)
    signal = signal.astype('int64')
    a.plot(np.arange(len(signal)), signal)
    a.set_title('Speech signal')
    a.set_xlabel('samples')
    a.set_ylabel('magtitude')

    energy = energy_in_frame(signal)
    b.plot(np.arange(len(energy)), energy)
    b.set_title('energy')
    b.set_xlabel('samples')
    b.set_ylabel('e')

    # c.plot(t, zcr)
    zcr = zero_crossing(signal)
    c.plot(np.arange(len(zcr)), zcr)
    c.set_title('zcr')
    c.set_xlabel('samples')
    c.set_ylabel('zcr')


    # a tk.DrawingArea
    canvas = FigureCanvasTkAgg(f, master=root)
    canvas.show()
    canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    # button = Tk.Button(master=root, text='Quit', command=sys.exit)
    button = Tk.Button(master=root, text='Quit', command=root.destroy)
    button.pack(side=Tk.BOTTOM)

    Tk.mainloop()

In [89]:
import Tkinter as Tk
from tkFileDialog import askopenfilename      

root = Tk.Tk()

def callback():
    file_name= askopenfilename() 
#     print file_name
    tk_lpc(file_name, root)
    
errmsg = 'Error!'
Tk.Button(text='File Open', command=callback).pack(fill=Tk.X)
# open_button.pack(fill=X)
Tk.mainloop()

In [ ]:
from audiolazy.lazy_filters import z, Stream
import wave
import numpy as np
import matplotlib.pyplot as plt
from audiolazy.lazy_analysis import window
import scipy.io.wavfile as wf
from audiolazy.lazy_lpc import acorr
from audiolazy.lazy_lpc import lpc

In [ ]:
def hamming_one_window(signal):
    return window.hamming(len(signal)) * signal

In [90]:
a = [1,2,3,4,5]

In [91]:
a[4:2]

[]